### ISSUE TITLE
Второй релиз до 23.04

### ISSUE THREAD

**Issue by nvamelichev** [pmolodyk/MinecraftFabricMod#3]
- [ ] **Юнит-тесты теперь обязательны (если ещё не сделаны &mdash; сделайте!)**
- [x] Уменьшить частоту построек
- [x] Увязать элементы дизайна вместе и заюзать их для генерации простых коробок. **Если получится сделать что-то посложнее, это будет преимуществом :-)**

**Comment by pmolodyk** [comment]
@nvamelichev
